apiVersion: v1
kind: Service
metadata:
  name: example-k8s
  namespace: default
  labels:
    app: example-k8s
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: example-k8s
