apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-k8s
  namespace: default
  labels:
    app: example-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-k8s
  template:
    metadata:
      labels:
        app: example-k8s
    spec:
      containers:
        - name: example-k8s
          image: cristhiankr/example-k8s:v1
          ports:
            - containerPort: 80
              name: http
